<?php

/**
 *  Implements hook_theme().
 */
function social_media_links_theme($existing, $type, $theme, $path) {
  return array(
    'social_media_links_platforms' => array(
      'variables' => array(
        'platforms' => array(),
        'appearance' => array(),
        'link_attributes' => array(),
      ),
    ),
  );
}

/**
 * Implements hook_preprocess_HOOK() for block.html.twig.
 */
function social_media_links_preprocess_block(&$variables) {
  if ($variables['plugin_id'] === 'social_media_links_block') {
    // Ensure that the css class "block-social-media-links" always exist,
    // no mather was theme is used. Because our styles use this class.
    $variables['attributes']['class'][] = 'block-social-media-links';
  }
}