<?php

/**
 * Implements hook_form_FORM_ID_alter().
 */
function report_broken_resource_form_contact_message_report_data_form_alter(&$form, &$form_state) {
  if(isset($_SERVER) && isset($_SERVER['HTTP_REFERER'])){
    $url = $_SERVER['HTTP_REFERER'];
    $url_text = "<a href=\"{$url}\">{$url}</a>";
  }
  else {
    $url = $url_text = 'Unknown URL';
  }

  $form['#prefix'] = sprintf('<div class="report-data-url">URL: %s</div>', $url_text );
  $form['field_url']['widget'][0]['value']['#default_value'] = $url;
  $form['field_url']['widget'][0]['value']['#type'] = 'hidden';
}